### ISSUE TITLE
[Bug]: Error after setting runes/essense modules to false. 

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/divinity#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when doing /prorpgitems reload an error pops up. It happened after setting runes/essence to false and having to update the worth and preset drop/loot files with-in. When trying to /prorpgitems reload this will appear. But reloading the modules themselves will work at this moment.

### Expected Behavior

A reload of the plugin.

### Environment

```markdown
- Server Software: 7900 Ryzen 9
- ProRPGItems Version: Latest
- ProMCCore Version: Latest
- Plugins:
```

### latest.log

- [Thu 07:56:48 ERROR Minecraft] null
org.bukkit.command.CommandException: Unhandled exception executing 'prorpgitems reload' in mc.promcteam.engine.commands.CommandRegister(prorpgitems)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
    at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
    at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
    at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
    at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
    at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
    at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101)
    at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435)
    at net.minecraft.commands.Commands.performCommand(Commands.java:336)
    at net.minecraft.commands.Commands.performCommand(Commands.java:323)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2236)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2196)
    at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452)
    a

**Comment by Travja** [comment]
I actually have runes and essences disabled on my local installation (I have for a while) and I'm not seeing this. Additionally, that stack-trace feels incomplete. Are you still facing this issue?

**Comment by DrHeretic** [comment]
No because I disabled them also. But seems to be an issue that only comes up when enabled

**Comment by Travja** [comment]
Wait... so how should this actually be set up for the error to occur then?

**Comment by Travja** [comment]
Closing due to lack of information
