### ISSUE TITLE
[Bug]: The properties module of the plugin is not working properly

### ISSUE THREAD

**Issue by Ghost067** [promcteam/divinity#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I updated the plugin to the latest version, the properties module of the plugin didn't work properly.

### Expected Behavior

Everything works fine with the properties module.

### Steps To Reproduce

1.0.4-R0.16更新至1.1.2-R0.1

### Environment

```markdown
- Server Software:PaperSpigot 1.16.5
- Divinity Version: Unknown
- Codex Version: Unknown
- Plugins:
```

### latest.log

[16:48:52 ERROR]: Could not pass event EntityDamageByEntityEvent to ProRPGItems v1.1.2-R0.1-SNAPSHOT
java.lang.NoSuchMethodError: 'boolean org.bukkit.persistence.PersistentDataContainer.has(org.bukkit.NamespacedKey)'
        at su.nightexpress.quantumrpg.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:73) ~[?:?]
        at su.nightexpress.quantumrpg.stats.bonus.StatBonus$1.fromPrimitive(StatBonus.java:26) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.get(CraftPersistentDataContainer.java:66) ~[patched_1.16.5.jar:git-Paper-794]
        at su.nightexpress.quantumrpg.stats.items.api.DuplicableItemLoreStat.lambda$getAllRaw$3(DuplicableItemLoreStat.java:192) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at su.nightexpress.quantumrpg.stats.items.api.DuplicableItemLoreStat.getAllRaw(DuplicableItemLoreStat.java:194) ~[?:?]
        at su.nightexpress.quantumrpg.stats.items.attributes.DamageAttribute.get(DamageAttribute.java:141) ~[?:?]
        at su.nightexpress.quantumrpg.stats.EntityStats.getDamageTypes(EntityStats.java:615) ~[?:?]
        at su.nightexpress.quantumrpg.manager.listener.object.VanillaWrapperListener.onVanillaDamage(VanillaWrapperListener.java:261) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor746.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at me.deecaad.weaponmechanics.weapon.damage.DamageUtil.apply(DamageUtil.java:132) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:117) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:51) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:45) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleEntityHit(HitHandler.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleHit(HitHandler.java:56) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.WeaponProjectile.updatePosition(WeaponProjectile.java:396) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.AProjectile.tick(AProjectile.java:361) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.run(ProjectilesRunnable.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[16:48:52 ERROR]: Could not pass event EntityDamageByEntityEvent to ProRPGItems v1.1.2-R0.1-SNAPSHOT
java.lang.NoClassDefFoundError: com/sucy/skill/api/DefaultCombatProtection
        at su.nightexpress.quantumrpg.modules.list.combatlog.CombatLogManager.onDamageIndicator(CombatLogManager.java:403) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor785.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at me.deecaad.weaponmechanics.weapon.damage.DamageUtil.apply(DamageUtil.java:132) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:117) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:51) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:45) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleEntityHit(HitHandler.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleHit(HitHandler.java:56) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.WeaponProjectile.updatePosition(WeaponProjectile.java:396) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.AProjectile.tick(AProjectile.java:361) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.run(ProjectilesRunnable.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Anything else?

When will the plugin be better adapted to WeaponMechaincs?

**Comment by Travja** [comment]
What version were you upgrading from?

**Comment by Ghost067** [comment]
From the plugin version 1.0.4-R0.16

**Comment by Travja** [comment]
Fixed in https://github.com/promcteam/divinity/commit/8d7f82413bfb29a870b611b90062771cf0f99025
